<template>
  <n-button v-if="config?.enabled" secondary type="primary" size="small" @click="show=true">{{ me?.authenticated ? me.user.displayName : '账号' }}</n-button>
  <Teleport to="body"><div v-if="show" class="account-overlay" @click.self="show=false"><section class="account-panel">
    <header><div><strong>{{ me?.authenticated ? me.user.displayName : '账号与云端工程' }}</strong><small v-if="me?.authenticated">{{ me.user.email }} · {{ me.user.role === 'admin' ? '管理员' : '用户' }}</small></div><button @click="show=false">✕</button></header>
    <template v-if="!me?.authenticated">
      <nav><button :class="{active:mode==='login'}" @click="mode='login'">登录</button><button v-if="config?.registrationEnabled" :class="{active:mode==='register'}" @click="mode='register'">注册</button><button :class="{active:mode==='reset'}" @click="mode='reset'">重置密码</button></nav>
      <form @submit.prevent="submitAuth">
        <label>邮箱<input v-model="form.email" autocomplete="email" type="email" required /></label>
        <label v-if="mode==='register'">显示名<input v-model="form.displayName" maxlength="80" /></label>
        <label>密码<input v-model="form.password" :autocomplete="mode==='login'?'current-password':'new-password'" type="password" minlength="10" required /></label>
        <label v-if="needsCode || mode!=='login'">邮件验证码<div class="inline"><input v-model="form.code" inputmode="numeric" maxlength="6" /><button type="button" @click="beginSendCode">发送验证码</button></div></label>
        <p v-if="error" class="error">{{ error }}</p><button class="primary" :disabled="busy">{{ busy ? '处理中…' : mode==='login' ? '登录' : mode==='register' ? '注册' : '重置密码' }}</button>
      </form>
    </template>
    <template v-else>
      <nav><button :class="{active:section==='projects'}" @click="section='projects';loadProjects()">云端工程</button><button :class="{active:section==='security'}" @click="section='security'">安全</button></nav>
      <div v-if="section==='projects'" class="projects">
        <div class="project-actions"><button class="primary" @click="saveCurrent">{{ currentProject ? '保存当前工程修订' : '保存当前记录到云端' }}</button><button v-if="currentProject" @click="currentProject=null">另存为新工程</button><button @click="loadProjects">刷新</button></div>
        <p v-if="!projects.length">暂时没有云端工程。</p>
        <article v-for="project in projects" :key="project.id"><div><strong>{{ project.title }}</strong><small>修订 {{ project.revision }} · {{ new Date(project.updatedAt).toLocaleString() }}</small></div><button @click="openProject(project.id)">打开</button><button v-if="project.sourceKey" @click="syncProject(project.id)">同步源</button><button class="danger" @click="deleteProject(project.id)">删除</button></article>
      </div>
      <form v-else @submit.prevent="changePassword"><label>当前密码<input v-model="passwordForm.current" type="password" required /></label><label>新密码<input v-model="passwordForm.next" type="password" minlength="10" required /></label><button class="primary">修改密码</button></form>
      <footer><a v-if="me.user.role==='admin'" href="/admin">账户管理</a><button @click="logout">退出登录</button></footer>
    </template>
  </section></div></Teleport>
  <Teleport to="body"><div v-if="captcha.show" class="captcha-overlay"><section><h3>人机验证</h3><p>发送邮件或异常行为需要先验证。</p><div v-if="captcha.provider==='image'"><div class="captcha-image" v-html="captcha.image"></div><input v-model="captcha.answer" placeholder="输入图中的字符" autocomplete="off" /></div><altcha-widget v-else-if="captcha.provider==='altcha'" ref="altchaEl" language="zh-cn" workers="1" @statechange="onAltchaState" /><div v-else ref="externalCaptcha"></div><p v-if="captcha.error" class="error">{{ captcha.error }}</p><footer><button @click="captcha.show=false">取消</button><button v-if="captcha.provider==='image'" class="primary" @click="verifyCaptcha">验证</button></footer></section></div></Teleport>
</template>

<script setup lang="ts">
import "altcha";
import { nextTick, onMounted, reactive, ref } from "vue";
import type { StoryArchive } from "~/story/types";
const props=defineProps<{archive?:StoryArchive}>();const emit=defineEmits<{load:[StoryArchive];sync:[any]}>();
type Config={enabled:boolean;registrationEnabled:boolean;captchaProvider:string;turnstileSiteKey:string;hcaptchaSiteKey:string};type Me={authenticated:boolean;user:any};
const show=ref(false),config=ref<Config>(),me=ref<Me>(),mode=ref<'login'|'register'|'reset'>('login'),section=ref<'projects'|'security'>('projects'),busy=ref(false),error=ref(''),needsCode=ref(false),projects=ref<any[]>([]),currentProject=ref<{id:string;revision:number}|null>(null),altchaEl=ref<any>(),externalCaptcha=ref<HTMLElement>();
const form=reactive({email:'',displayName:'',password:'',code:'',codeId:'',riskClearance:''});const passwordForm=reactive({current:'',next:''});const captcha=reactive({show:false,id:'',provider:'image',image:'',answer:'',payload:'',token:'',error:'',purpose:'login',scope:'verification-send'});
let pendingRetry:(()=>Promise<void>)|null=null;
function csrf(){return decodeURIComponent(document.cookie.split('; ').find(v=>v.startsWith('scardice_account_csrf='))?.split('=').slice(1).join('=')||'')}
async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);if(options.body)headers.set('Content-Type','application/json');const token=csrf();if(token)headers.set('X-CSRF-Token',token);if(form.riskClearance&&!headers.has('X-Captcha-Clearance'))headers.set('X-Captcha-Clearance',form.riskClearance);const response=await fetch(path,{...options,headers,credentials:'same-origin'});const data=await response.json().catch(()=>({error:'invalid_response'}));if(!response.ok){const exception:any=new Error(data.error||'request_failed');exception.data=data;exception.status=response.status;throw exception}if(headers.has('X-Captcha-Clearance'))form.riskClearance='';return data}
async function refreshMe(){me.value=await request('/api/account/me');if(me.value?.authenticated)loadProjects()}
function readable(err:any){const data=err?.data||{};if(data.error==='account_banned')return `账号已被封禁：${data.reason||'未提供原因'}${data.until?`（至 ${data.until}）`:''}`;const map:any={invalid_credentials:'邮箱或密码不正确',email_verification_required:'这是新设备或新网段，请发送并填写邮件验证码',verification_invalid:'验证码不正确或已过期',smtp_not_configured:'管理员尚未配置 SMTP',captcha_required:'请先完成人机验证',account_exists:'账号已存在',registration_unavailable:'该邮箱无法注册',reset_invalid:'重置资料或验证码无效'};return map[data.error||err?.message]||'操作失败，请稍后重试'}
async function submitAuth(){busy.value=true;error.value='';try{if(mode.value==='login'){const data=await request('/api/account/login',{method:'POST',headers:form.riskClearance?{'X-Captcha-Clearance':form.riskClearance}:{},body:JSON.stringify({email:form.email,password:form.password,codeId:form.codeId,code:form.code})});form.riskClearance='';me.value={authenticated:true,user:data.user}}else if(mode.value==='register'){const data=await request('/api/account/register',{method:'POST',body:JSON.stringify({...form})});me.value={authenticated:true,user:data.user}}else{await request('/api/account/password/reset',{method:'POST',body:JSON.stringify({email:form.email,password:form.password,codeId:form.codeId,code:form.code})});mode.value='login';error.value='密码已重置，请登录'}if(me.value?.authenticated)loadProjects()}catch(err:any){if(err.data?.error==='email_verification_required')needsCode.value=true;if(err.data?.error==='captcha_required')await beginCaptcha(String(err.data.scope||'login'),submitAuth);error.value=readable(err)}finally{busy.value=false}}
async function beginSendCode(){captcha.purpose=mode.value==='register'?'register':mode.value==='reset'?'reset-password':'login';await beginCaptcha('verification-send')}
async function beginCaptcha(scope:string,retry:(()=>Promise<void>)|null=null){captcha.scope=scope;pendingRetry=retry;captcha.error='';const challenge=await request('/api/account/captcha/challenge',{method:'POST',body:'{}'});Object.assign(captcha,{show:true,id:challenge.id,provider:challenge.provider,image:challenge.image||'',answer:'',payload:'',token:''});await nextTick();if(challenge.provider==='altcha'){altchaEl.value?.configure?.({challenge:challenge.challenge,workers:1,language:'zh-cn'})}else if(challenge.provider==='turnstile'||challenge.provider==='hcaptcha'){renderExternal(challenge.provider,challenge.siteKey)}}
async function renderExternal(provider:string,siteKey:string){const globalName=provider==='turnstile'?'turnstile':'hcaptcha';const src=provider==='turnstile'?'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit':'https://js.hcaptcha.com/1/api.js?render=explicit';if(!(globalThis as any)[globalName])await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src=src;script.async=true;script.onload=()=>resolve();script.onerror=()=>reject();document.head.append(script)});await nextTick();(globalThis as any)[globalName].render(externalCaptcha.value,{sitekey:siteKey,callback:(token:string)=>{captcha.token=token;verifyCaptcha()}})}
function onAltchaState(event:CustomEvent){if(event.detail?.state==='verified'){captcha.payload=event.detail.payload;verifyCaptcha()}}
async function verifyCaptcha(){try{captcha.error='';const data=await request('/api/account/captcha/verify',{method:'POST',body:JSON.stringify({id:captcha.id,answer:captcha.answer,payload:captcha.payload,token:captcha.token,email:form.email,scope:captcha.scope})});if(captcha.scope!=='verification-send'){form.riskClearance=data.clearance;captcha.show=false;error.value='验证成功，正在重试刚才的操作';const retry=pendingRetry;pendingRetry=null;if(retry)await retry();return}const sent=await request('/api/account/verification/send',{method:'POST',body:JSON.stringify({email:form.email,purpose:captcha.purpose,captchaClearance:data.clearance})});form.codeId=sent.id;needsCode.value=true;captcha.show=false;error.value='验证码已发送，请检查邮箱'}catch(err){captcha.error=readable(err)}}
function bytesToBase64(bytes:Uint8Array){let value='';for(let i=0;i<bytes.length;i+=0x8000)value+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(value)}
function packArchive(){if(!props.archive)return null;return{story:props.archive.document,assets:[...props.archive.assets].map(([id,bytes])=>[id,bytesToBase64(bytes)])}}
function unpackArchive(value:any):StoryArchive{const wrapped=value?.story?value:{story:value,assets:[]};return{document:wrapped.story,assets:new Map((wrapped.assets||[]).map(([id,text]:[string,string])=>[id,Uint8Array.from(atob(text),c=>c.charCodeAt(0))]))}}
async function loadProjects(){if(!me.value?.authenticated)return;try{projects.value=await request('/api/account/projects')}catch{projects.value=[]}}
async function saveCurrent(){const packed=packArchive();if(!packed)return;try{const base={title:props.archive?.document.title,document:packed,sourceKey:props.archive?.document.source.key||'',sourceRevision:props.archive?.document.source.revision||'',sourceSecret:props.archive?.document.source.key?location.hash.slice(1):''};const saved=currentProject.value?await request(`/api/account/projects/${encodeURIComponent(currentProject.value.id)}`,{method:'PUT',body:JSON.stringify({...base,revision:currentProject.value.revision})}):await request('/api/account/projects',{method:'POST',body:JSON.stringify(base)});currentProject.value={id:saved.id,revision:saved.revision};await loadProjects()}catch(err:any){if(err.data?.error==='captcha_required')await beginCaptcha(err.data.scope||'project-write',saveCurrent);error.value=readable(err)}}
async function openProject(id:string){try{const project=await request(`/api/account/projects/${encodeURIComponent(id)}`);currentProject.value={id:project.id,revision:project.revision};emit('load',unpackArchive(project.document));show.value=false}catch(err){error.value=readable(err)}}
async function syncProject(id:string){try{const value=await request(`/api/account/projects/${encodeURIComponent(id)}/source`);emit('sync',value);show.value=false}catch(err){error.value='源日志已失效、密钥不正确或不可访问'}}
async function deleteProject(id:string){if(!confirm('确定删除这个云端工程吗？'))return;try{await deleteProjectConfirmed(id)}catch(err:any){if(err.data?.error==='captcha_required')await beginCaptcha(err.data.scope||'project-delete',()=>deleteProjectConfirmed(id));error.value=readable(err)}}
async function deleteProjectConfirmed(id:string){await request(`/api/account/projects/${encodeURIComponent(id)}`,{method:'DELETE'});if(currentProject.value?.id===id)currentProject.value=null;await loadProjects()}
async function changePassword(){try{await request('/api/account/password',{method:'POST',body:JSON.stringify({currentPassword:passwordForm.current,password:passwordForm.next})});me.value={authenticated:false,user:null};error.value='密码已修改，请重新登录'}catch(err:any){if(err.data?.error==='captcha_required')await beginCaptcha(err.data.scope||'password-change',changePassword);error.value=readable(err)}}
async function logout(){try{await request('/api/account/logout',{method:'POST',body:'{}'})}finally{me.value={authenticated:false,user:null}}}
onMounted(async()=>{try{config.value=await request('/api/account/config');await refreshMe()}catch{config.value={enabled:false,registrationEnabled:false,captchaProvider:'image',turnstileSiteKey:'',hcaptchaSiteKey:''}}});
</script>

<style scoped>
.account-overlay,.captcha-overlay{position:fixed;inset:0;z-index:10020;display:grid;place-items:center;padding:1rem;background:rgba(0,0,0,.68)}.account-panel{width:min(560px,100%);max-height:90vh;overflow:auto;border-radius:20px;background:#17201f;color:#edf3f2;box-shadow:0 20px 80px #0008}.account-panel>header{display:flex;justify-content:space-between;align-items:center;padding:1.1rem 1.25rem}.account-panel>header div{display:grid}.account-panel small{opacity:.62}.account-panel nav{display:flex;border-block:1px solid #33413f}.account-panel button,.captcha-overlay button{border:0;border-radius:9px;padding:.58rem .8rem;background:#293634;color:inherit;cursor:pointer}.account-panel nav button{flex:1;border-radius:0;background:transparent}.account-panel nav button.active{box-shadow:inset 0 -3px #38bfc8}.account-panel form,.projects{display:grid;gap:.9rem;padding:1.2rem}.account-panel label{display:grid;gap:.35rem}.account-panel input{border:1px solid #465553;border-radius:10px;background:#0f1615;color:inherit;padding:.7rem}.account-panel .inline{display:flex;gap:.5rem}.inline input{flex:1;min-width:0}.account-panel .primary,.captcha-overlay .primary{background:#168a92}.error{color:#ff9f9f}.projects article{display:flex;align-items:center;gap:.5rem;padding:.7rem;border:1px solid #33413f;border-radius:12px}.projects article div{display:grid;flex:1}.project-actions,.account-panel>footer{display:flex;gap:.5rem;justify-content:flex-end}.account-panel>footer{padding:1rem 1.2rem;border-top:1px solid #33413f}.account-panel>footer a{margin-right:auto;color:#65d8df}.danger{color:#ff9f9f!important}.captcha-overlay section{width:min(380px,100%);padding:1.2rem;border-radius:18px;background:#17201f;color:#edf3f2}.captcha-image{display:grid;place-items:center;background:#eef2f7;border-radius:10px;overflow:hidden}.captcha-overlay input{box-sizing:border-box;width:100%;margin-top:.7rem;padding:.7rem;border-radius:10px}.captcha-overlay footer{display:flex;justify-content:flex-end;gap:.5rem;margin-top:1rem}@media(max-width:520px){.account-panel{border-radius:14px}.projects article{align-items:flex-start;flex-wrap:wrap}}
</style>
