<template>
  <Teleport to="body">
    <div v-if="show" class="player" :class="[`player--${document.settings.theme}`, `player--${document.settings.density}`]" :style="playerStyle">
      <header><button @click="$emit('close')">← 返回</button><div><strong>{{ document.title }}</strong><small>{{ visibleCount }} / {{ document.messages.length }}</small></div><button @click="toggle">{{ !autoplay ? (visibleCount ? '下一条' : '开始') : running ? '暂停' : visibleCount ? '继续' : '开始' }}</button></header>
      <main ref="scrollEl" :style="canvasStyle">
        <TransitionGroup :name="document.settings.animation === 'none' ? '' : document.settings.animation">
          <article v-for="(message,index) in visibleMessages" :key="message.id" class="player-message" :class="[`player-message--${character(message.characterId)?.position || 'left'}`, { 'player-message--merged': merged(index) }]">
            <span v-if="showAvatar(message.characterId,index)" class="player-avatar"><img v-if="avatar(character(message.characterId))" :src="avatar(character(message.characterId))" alt="" /><i v-else>{{ character(message.characterId)?.name?.slice(0,1) || '旁' }}</i></span>
            <div><small v-if="(document.settings.showNames && !merged(index)) || document.settings.showTime"><template v-if="document.settings.showNames && !merged(index)">{{ character(message.characterId)?.name }}<template v-if="document.settings.showQqInPreview && character(message.characterId)?.imUserId"> · {{ character(message.characterId)?.imUserId }}</template></template><template v-if="document.settings.showTime">{{ document.settings.showNames && !merged(index) ? ' · ' : '' }}{{ messageTime(message) }}</template></small><div class="bubble"><img v-if="message.kind === 'image'" :src="imageUrl(message.asset)" :alt="message.alt || '图片'" /><span v-else>{{ message.text }}</span></div></div>
          </article>
        </TransitionGroup>
      </main>
      <footer>
        <label><input v-model="autoplay" type="checkbox" /> 自动播放</label>
        <select v-model="timing"><option value="dynamic">按字数动态</option><option value="fixed">固定间隔</option></select>
        <input v-if="timing === 'fixed'" v-model.number="fixedMs" aria-label="固定播放间隔毫秒" type="number" min="500" max="30000" step="250" />
        <label v-else>字/分钟 <input v-model.number="readingSpeed" aria-label="中文阅读速度" type="number" min="80" max="1000" step="20" /></label>
        <input v-model.number="width" class="width" type="range" min="360" max="1200" step="20" />
      </footer>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from "vue";
import { playbackDelay } from "~/story/model";
import type { StoryArchive, StoryAssetRef, StoryCharacter, StoryMessage } from "~/story/types";
const props = defineProps<{ show: boolean; archive: StoryArchive; assetUrl: (id: string) => string }>();
defineEmits<{ close: [] }>();
const document = computed(() => props.archive.document); const visibleCount = ref(0); const running = ref(false); const autoplay = ref(document.value.settings.autoplay); const timing = ref(document.value.settings.playbackTiming); const fixedMs = ref(document.value.settings.fixedDelayMs); const readingSpeed = ref(document.value.settings.chineseCharsPerMinute); const width = ref(document.value.settings.canvasWidth); const scrollEl = ref<HTMLElement>(); let timer = 0;
const visibleMessages = computed(() => document.value.messages.slice(0,visibleCount.value)); const canvasStyle = computed(() => ({'--canvas-width':`${width.value}px`,'--bubble-width':`${document.value.settings.bubbleMaxWidth}%`,'--font-size':`${document.value.settings.fontSize}px`}));const playerStyle=computed(()=>({'--animation-duration':`${document.value.settings.animationDurationMs}ms`}));
function character(id:string){return document.value.characters.find(c=>c.id===id)} function assetUrl(asset?:StoryAssetRef){return asset ? (props.archive.assets.has(asset.id)?props.assetUrl(asset.id):asset.sourceUrl||asset.id) : ''} function avatar(c?:StoryCharacter){return assetUrl(c?.avatar)||(c?.imUserId?`/api/editor/avatar/qq/${encodeURIComponent(c.imUserId)}`:"")} function imageUrl(asset:StoryAssetRef){return assetUrl(asset)}
function merged(index:number){if(!document.value.settings.mergeMessages||index===0)return false;const current=document.value.messages[index],previous=document.value.messages[index-1],c=character(current.characterId);return current.characterId===previous.characterId&&(!c?.isNarrator||document.value.settings.mergeNarration)}function mergedWithNext(index:number){if(!document.value.settings.mergeMessages||index>=visibleMessages.value.length-1)return false;const current=document.value.messages[index],next=document.value.messages[index+1],c=character(current.characterId);return current.characterId===next.characterId&&(!c?.isNarrator||document.value.settings.mergeNarration)}
function showAvatar(id:string,index:number){const c=character(id);if(!document.value.settings.showAvatars||(!document.value.settings.showNarratorAvatar&&c?.isNarrator))return false;return document.value.settings.avatarAlignment==='bottom'?!mergedWithNext(index):!merged(index)}function messageTime(message:StoryMessage){if(message.timeText)return message.timeText;if(!message.time)return '--:--';const value=message.time>10_000_000_000?message.time:message.time*1000;return new Date(value).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function dynamicDelay(message:StoryMessage){const settings={...document.value.settings,chineseCharsPerMinute:Math.max(80,readingSpeed.value||280)};return playbackDelay(message,{...document.value,settings})}
function stop(){running.value=false;window.clearTimeout(timer)} function schedule(){window.clearTimeout(timer);if(!running.value||!autoplay.value)return;if(visibleCount.value>=document.value.messages.length){stop();return}const msg=document.value.messages[visibleCount.value];timer=window.setTimeout(()=>{next();schedule()},timing.value==='fixed'?fixedMs.value:dynamicDelay(msg))}
function next(){visibleCount.value=Math.min(document.value.messages.length,visibleCount.value+1);nextTick(()=>scrollEl.value?.scrollTo({top:scrollEl.value.scrollHeight,behavior:'smooth'}))} function toggle(){if(!autoplay.value){next();return}if(!visibleCount.value)next();running.value=!running.value;schedule()}
watch(()=>props.show,(show)=>{stop();visibleCount.value=show?0:visibleCount.value});watch([autoplay,timing,fixedMs,readingSpeed],schedule);onBeforeUnmount(stop);
</script>

<style scoped>
.player{position:fixed;inset:0;z-index:10000;display:grid;grid-template-rows:auto 1fr auto;background:#0b1110;color:#eef2f1}.player--light{background:#eef2f7;color:#17202a}.player header,.player footer{display:flex;align-items:center;gap:1rem;padding:max(.8rem,env(safe-area-inset-top)) max(1rem,env(safe-area-inset-right));background:rgba(20,29,28,.96);color:white}.player header{justify-content:space-between}.player header div{display:grid;text-align:center}.player header small{opacity:.65}.player button,.player select,.player input{border:0;border-radius:10px;padding:.6rem .8rem;background:#2b3837;color:inherit}.player main{width:min(var(--canvas-width),100%);margin:auto;padding:clamp(1rem,3vw,2.5rem);overflow-y:auto;scrollbar-gutter:stable}.player-message{display:flex;align-items:flex-start;gap:.7rem;margin:.45rem 0;font-size:var(--font-size)}.player-message--merged{margin-top:-.2rem}.player-avatar{width:42px;height:42px;border-radius:50%;overflow:hidden;display:grid;place-items:center;flex:0 0 42px;background:#334342}.player-avatar img{width:100%;height:100%;object-fit:cover}.player-avatar i{font-style:normal}.player-message>div{max-width:var(--bubble-width)}.player-message small{display:block;opacity:.7;margin:0 .35rem .25rem}.bubble{padding:.75rem 1rem;border-radius:18px;background:#182120;white-space:pre-wrap;overflow-wrap:anywhere}.bubble img{display:block;max-width:100%;max-height:72vh;border-radius:14px}.player-message--right{flex-direction:row-reverse;text-align:right}.player-message--right .bubble{background:#1f4f52}.player-message--narrator{justify-content:center;text-align:center}.player-message--narrator .bubble{background:#252c2b;color:#c5cfcd;border-radius:10px}.player--compact .player-message{margin:.25rem 0}.player--compact .bubble{padding:.5rem .75rem}.player--spacious .player-message{margin:.85rem 0}.player--spacious .bubble{padding:.95rem 1.15rem}.player footer{justify-content:center;flex-wrap:wrap;padding-bottom:max(.8rem,env(safe-area-inset-bottom))}.player footer label{display:flex;align-items:center;gap:.4rem}.width{width:min(260px,38vw)}.slide-fade-enter-active,.fade-enter-active{transition:var(--animation-duration,.28s) ease}.slide-fade-enter-from{opacity:0;transform:translateY(18px)}.fade-enter-from{opacity:0}@media(prefers-color-scheme:light){.player--auto{background:#eef2f7;color:#17202a}}@media(max-width:600px){.player footer .width{display:none}.player main{width:100%;padding:1rem}.player-message>div{max-width:82%}}
</style>
